version: "3.6"

networks:
  net:

volumes:
  postgres_data:
  transformers_cache:

services:
  server:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    links:
      - db:db
    environment:
      PGRST_DB_URI: postgres://${DB_USER}:${DB_PASSWORD}@localhost:5432/${DB_NAME}
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: ${DB_USER}
      PGRST_SERVER_PROXY_URI: "http://localhost:3000"
    networks:
      - net
    depends_on:
      - db
  
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - net
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready -U ${DB_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5
  
